"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

fib_array = [0,1]

current_fib = fib_array[-2] + fib_array[-1]

even_sum = 0

while current_fib < 4_000_000:
    fib_array.append(current_fib)
    current_fib = fib_array[-2] + fib_array[-1]
    if current_fib % 2 == 0:
        even_sum += current_fib

print(even_sum)